---
- name: Deploy VMs with terraform
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: write vars from env
      copy: 
        content: 
          pve: "{{ pve }}"
          template: "{{ template }}"
          eznode: "{{ eznode }}"
          settings: "{{ settings }}"
          ezua: "{{ ezua }}"
          ezdf: "{{ ezdf }}"
        dest: ./lab.tfvars.json

    - name: Create resources using terraform
      cloud.terraform.terraform:
        project_path: '{{ playbook_dir }}/tf'
        complex_vars: true
        variables_files: "../lab.tfvars.json"
        force_init: true
        state: present
      register: terraform_returns

    - name: clean up known hosts
      ansible.builtin.known_hosts:
        name: "{{ item.value }}"
        state: absent
      with_dict: "{{ (terraform_returns.outputs.df_nodes | ansible.builtin.combine(terraform_returns.outputs.ua_nodes, list_merge='append', recursive=true)).value }}"
