---
- name: Remove VMs using terraform
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: write vars from env
      copy: 
        content: 
          pve: "{{ pve }}"
          template: "{{ template }}"
          eznode: "{{ eznode }}"
          settings: "{{ settings }}"
          ezua: "{{ ezua }}"
          ezdf: "{{ ezdf }}"
        dest: ./lab.tfvars.json

    - name: Destroy resources using terraform
      cloud.terraform.terraform:
        project_path: '{{ playbook_dir }}/tf'
        complex_vars: yes
        variables_files: "../lab.tfvars.json"
        state: absent

    - name: Delete artifacts
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/clusterConfig.yaml
        - /tmp/ezkf-input.yaml
        - /tmp/ezkf-orch-status.txt
        - /tmp/ezkfWorkloadDeploy.yaml
        - /tmp/hostPoolConfig.yaml
        - /tmp/mgmt-kubeconfig
        - /tmp/prechecksStatus.txt
        - /tmp/ua-prechecks.yaml
