---
- name: Prepare DF nodes
  hosts: datafabric
  become: true

  tasks:
    - name: Clear known hosts to avoid host conflicts
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        state: absent
      delegate_to: 127.0.0.1
      become: false

    - name: Set timezone
      community.general.timezone:
        name: "{{ settings | from_json | json_query('timezone') }}"

    - name: Enable Password Authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present
        backup: true
      notify:
        - restart ssh

    - name: Enable Root Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?\s?PermitRootLogin.*$'
        line: "PermitRootLogin yes"
        state: present
        backup: true
      notify:
        - restart ssh

    - name: Remove cloud-init Root login prevention
      replace:
        path: /root/.ssh/authorized_keys
        regexp: '^.*?(ssh-rsa .*)$'
        replace: '\1'

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
