---

- hosts: localhost
  gather_facts: false
  # tasks:
  #   - ansible.builtin.debug:
  #       msg: Starting UA Deployment

  tasks:
    - name: write vars from env
      copy: 
        content: 
          pve: "{{ pve }}"
          template: "{{ template }}"
          eznode: "{{ eznode }}"
          settings: "{{ settings }}"
          ezua: "{{ ezua }}"
          ezdf: "{{ ezdf }}"
        dest: "tf/terraform.tfvars.json"

- name: Create VMs
  ansible.builtin.import_playbook: playbooks/infra/vms-create.yml
  # vars:
  #   nodes: 5

- name: Preconfiguration
  ansible.builtin.import_playbook: playbooks/ua/prepare.yml

- name: Installation
  ansible.builtin.import_playbook: playbooks/ua/install.yml
