---

- name: Install DF as it is required
  ansible.builtin.import_playbook: playbooks/df/install.yml

- name: Install UA
  ansible.builtin.import_playbook: playbooks/ua/install.yml
  vars:
    ezfabrelease: ~/ezfab-release.tgz
    ezfabricctl_cmd: /usr/local/bin/ezfabricctl
