---

- name: Install Unified Analytics
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Write vars from env
      ansible.builtin.copy:
        content:
          pve: {{ pve }}
          template: {{ template }}
          eznode: {{ eznode }}
          settings: {{ settings }}
          ezua: {{ ezua }}
          ezdf: {{ ezdf }}
        dest: "tf/terraform.tfvars.json"

- name: Setup UA nodes
  ansible.builtin.import_playbook: playbooks/ua/prepare.yml

- name: External DF
  ansible.builtin.import_playbook: playbooks/ua/setup-df.yml

- name: Installation
  ansible.builtin.import_playbook: playbooks/ua/install.yml
  vars:
    ezfabrelease: ~/ezfab-release.tgz
    ezfabricctl_cmd: /usr/local/bin/ezfabricctl
