---

# Install DF and UA playbooks
- name: Install DF Playbook
  ansible.builtin.import_playbook: playbooks/df/install.yml

- name: Install UA Playbook
  ansible.builtin.import_playbook: playbooks/ua/install.yml
