---
- name: Prepare UA nodes
  hosts: localhost
  connection: local

  vars:
    - no_proxy: "10.96.0.0/12,10.224.0.0/16,10.43.0.0/16,192.168.0.0/16,.external.hpe.local,localhost,.cluster.local,.svc,.default.svc,127.0.0.1,169.254.169.254,{{ groups['ua_controllers'][0] }},{{ groups['ua_controllers'][1] }},.{{ settings['domain'] }}"

    - auth_data:
        admin_user:
          fullname: Ezmeral Admin
          email: "ezadmin@{{ settings['domain'] }}"
          password: "{{ ezua['password'] }}"
          username: "{{ ezua['username'] }}"

  tasks:
    - name: Precheck Stanza
      ansible.builtin.template:
        src: ./templates/ua-precheck.yml.j2
        dest: /tmp/ua-prechecks.yaml
      vars:
        - username: "{{ settings['username'] | default('admin') }}"
        - password_b64: "{{ settings['password'] | default('Admin123.') | b64encode }}"
        - orchestrator: "{{ groups['ua_controllers'][0] }}"
        - controlplane: "{{ groups['ua_controllers'][1] }}"
        - workers: "{{ groups['ua_workers'] }}"

# {ezfabricctl_cmd} pc -i /tmp/ua-prechecks.yaml -s /tmp/prechecksStatus.txt

    - name: EzkfInput Stanza
      ansible.builtin.template:
        src: ./templates/ua-ezkfInput.yml.j2
        dest: /tmp/ezkf-input.yaml
      vars:
        - username: "{{ ezua['username'] | default('admin') }}"
        - password_b64: "{{ ezua['password'] | default('Admin123.') | b64encode }}"
        - registryUrl: "{{ ezua['registryUrl'] | default('') }}"
        - registryInsecure: "{{ ezua['registryInsecure'] | default('false') }}"
        - controller: "{{ groups['ua_controllers'][0] }}"
        - http_proxy: "{{ settings['proxy'] | default('') }}"
        - https_proxy: "{{ settings['proxy'] | default('') }}"
        - no_proxy: "{{ settings['no_proxy'] | default('') }}"

# {ezfabricctl_cmd} o init -p ./ezfab-release.tgz -i /tmp/ezkf-input.yaml -s ./.ezlab/ezkf-orch-status.txt --save-kubeconfig ./.ezlab/mgmt-kubeconfig

    - name: HostPoolConfig Stanza
      ansible.builtin.template:
        src: ./templates/ua-hostPoolConfig.yml.j2
        dest: /tmp/hostPoolConfig.yaml
      vars:
        - username: "{{ ezua['username'] | default('admin') }}"
        - password_b64: "{{ ezua['password'] | default('Admin123.') | b64encode }}"
        - controller: "{{ groups['ua_controllers'][1] }}"
        - workers: "{{ groups['ua_workers'] }}"

# {ezfabricctl_cmd} ph i -i /tmp/hostPoolConfig.yaml -c ./.ezlab/mgmt-kubeconfig -s ./.ezlab/hostPoolConfigStatus.txt

    - name: ClusterConfig Stanza
      ansible.builtin.template:
        src: ./templates/ua-clusterConfig.yml.j2
        dest: /tmp/clusterConfig.yaml
      vars:
        - cluster_name: "{{ settings['cluster_name'] | default('ua') }}"
        - controller: "{{ groups['ua_controllers'][1] }}"
        - registryUrl: "{{ settings['registryUrl'] | default('') }}"
        - registryInsecure: "{{ settings['registryInsecure'] | default('false') }}"

# {ezfabricctl_cmd} w i -i /tmp/clusterConfig.yaml -c ./.ezlab/mgmt-kubeconfig -s ./.ezlab/clusterConfigStatus.txt

### GET CLUSTER KUBECONFIG
# ezfabricctl_cmd} w g k -n {APPCONFIG[UA].get('clustername', 'ezlab')} -i ./.ezlab/clusterConfig.yaml -c ./.ezlab/mgmt-kubeconfig -s ./.ezlab/clusterConfigStatus.txt --save-kubeconfig /tmp/workload-kubeconfig


    - name: WorkloadDeploy Stanza
      ansible.builtin.template:
        src: ./templates/ua-ezkfWorkloadDeploy.yml.j2
        dest: /tmp/ezkfWorkloadDeploy.yaml
      vars:
        - registryUrl: "{{ ezua['registryUrl'] | default('') }}"
        - registryInsecure: "{{ ezua['registryInsecure'] | default('false') }}"
        - registryCaFile: "{{ ezua['registryCaFile'] | default('') }}"
        - registryUsername: "{{ ezua['registryUsername'] | default('') }}"
        - registryPassword_b64: "{{ settings['registryPassword'] | default('') | b64encode }}"
        - clustername: "{{ ezua['clustername'] | default('ezlab') }}"
        - auth_data: "{{ auth_data | from_yaml | b64encode }}"
        - domain: "{{ settings['domain'] | default('') }}"
        - http_proxy: "{{ settings['proxy'] | default('') }}"
        - https_proxy: "{{ settings['proxy'] | default('') }}"
        - no_proxy: "{{ settings['no_proxy'] | default( no_proxy ) }}"

# {kubectl_cmd} --kubeconfig=/tmp/workload-kubeconfig apply -f /tmp/ezkfWorkloadDeploy.yaml
