---
- name: Install UA
  hosts: localhost
  connection: local

  vars:
    # Generic params
    - sshusername: "{{ settings['username'] | default('ezmeral') }}"
    - sshpassword_b64: "{{ settings['password'] | default('Admin123.') | trim | b64encode }}"

    - domain: "{{ settings['domain'] | default('ezmeral.lab') }}"

    - http_proxy: "{{ settings['proxy'] | default('') }}"
    - https_proxy: "{{ settings['proxy'] | default('') }}"
    - no_proxy: "10.96.0.0/12,10.224.0.0/16,10.43.0.0/16,192.168.0.0/16,.external.hpe.local,localhost,.cluster.local,.svc,.default.svc,127.0.0.1,169.254.169.254,{{ groups['all'] | join(',') }},.{{ domain }}"

    # EZUA params
    - clustername: "{{ ezua['clustername'] | default('ezlab') }}"
    - orchestrator: "{{ hostvars[groups['ua_controllers'][0]]['ansible_host'] }}"
    - master: "{{ hostvars[groups['ua_controllers'][1]]['ansible_host'] }}"
    - workers: "{{ groups['ua_workers'] | map('extract', hostvars, ['ansible_host']) }}"

    - ezusername: "{{ ezua['username'] | default('admin') }}"
    - ezpassword_b64: "{{ ezua['password'] | default('Admin123.') | trim | b64encode }}"

    - auth_data:
        admin_user:
          fullname: Ezmeral Admin
          email: "ezadmin@{{ settings['domain'] }}"
          username: "{{ ezusername }}"
          password: "{{ ezua['password'] | default('Admin123.') }}"

    - authdata_b64: "{{ auth_data | from_yaml | trim | b64encode }}"

    - registryUrl: "{{ ezua['registryUrl'] | default('') }}"
    - registryInsecure: "{{ ezua['registryInsecure'] | default('false') }}"
    - registryCaFile: "{{ ezua['registryCaFile'] }}"
    - registryUsername: "{{ ezua['registryUsername'] }}"
    - registryPassword_b64: "{{ settings['registryPassword'] | trim | b64encode }}"

  tasks:
    - name: Copy stanza files
      ansible.builtin.template:
        src: "../../templates/{{ item }}"
        dest: "/tmp/{{ item | replace('.j2', '') }}"
      with_items:
        - ua-prechecks.yml.j2
        - ua-ezkfInput.yml.j2
        - ua-hostPoolConfig.yml.j2
        - ua-clusterConfig.yml.j2
        - ua-ezkfWorkloadDeploy.yml.j2

    # - name: Precheck Stanza
    #   ansible.builtin.template:
    #     src: "../../templates/ua-precheck.yml.j2"
    #     dest: /tmp/ua-prechecks.yaml

    # - name: EzkfInput Stanza
    #   ansible.builtin.template:
    #     src: "../../templates/ua-ezkfInput.yml.j2"
    #     dest: /tmp/ezkf-input.yaml

    # - name: HostPoolConfig Stanza
    #   ansible.builtin.template:
    #     src: "../../templates/ua-hostPoolConfig.yml.j2"
    #     dest: /tmp/hostPoolConfig.yaml

    # - name: ClusterConfig Stanza
    #   ansible.builtin.template:
    #     src: "../../templates/ua-clusterConfig.yml.j2"
    #     dest: /tmp/clusterConfig.yaml

    # - name: WorkloadDeploy Stanza
    #   ansible.builtin.template:
    #     src: "../../templates/ua-ezkfWorkloadDeploy.yml.j2"
    #     dest: /tmp/ezkfWorkloadDeploy.yaml

    # - name: Build ezkf clusters
    #   ansible.builtin.shell:
    #     cmd: |
    #       set -euo pipefail
    #       {{ ezfabricctl_cmd }} pc -i /tmp/ua-prechecks.yaml -s /tmp/prechecksStatus.txt
    #       {{ ezfabricctl_cmd }} o init -p {{ ezfabrelease }} -i /tmp/ezkf-input.yaml -s /tmp/ezkf-orch-status.txt --save-kubeconfig /tmp/mgmt-kubeconfig
    #       {{ ezfabricctl_cmd }} ph i -i /tmp/hostPoolConfig.yaml -c /tmp/mgmt-kubeconfig -s /tmp/hostPoolConfigStatus.txt
    #       {{ ezfabricctl_cmd }} w i -i /tmp/clusterConfig.yaml -c /tmp/mgmt-kubeconfig -s /tmp/clusterConfigStatus.txt
    #       {{ ezfabricctl_cmd }} w g k -n {{ clustername }} -i /tmp/clusterConfig.yaml -c /tmp/mgmt-kubeconfig -s /tmp/clusterConfigStatus.txt --save-kubeconfig /tmp/workload-kubeconfig
    #       kubectl --kubeconfig=/tmp/workload-kubeconfig apply -f /tmp/ezkfWorkloadDeploy.yaml

    - name: Write deployment script
      ansible.builtin.copy:
        content: |
          set -euo pipefail
          {{ ezfabricctl_cmd }} pc -i /tmp/ua-prechecks.yml -s /tmp/prechecksStatus.txt
          {{ ezfabricctl_cmd }} o init -p {{ ezfabrelease }} -i /tmp/ua-ezkfInput.yml -s /tmp/ezkf-orch-status.txt --save-kubeconfig /tmp/mgmt-kubeconfig
          {{ ezfabricctl_cmd }} ph i -i /tmp/ua-hostPoolConfig.yml -c /tmp/mgmt-kubeconfig -s /tmp/hostPoolConfigStatus.txt
          {{ ezfabricctl_cmd }} w i -i /tmp/ua-clusterConfig.yml -c /tmp/mgmt-kubeconfig -s /tmp/clusterConfigStatus.txt
          {{ ezfabricctl_cmd }} w g k -n {{ clustername }} -i /tmp/ua-clusterConfig.yml -c /tmp/mgmt-kubeconfig -s /tmp/clusterConfigStatus.txt --save-kubeconfig /tmp/workload-kubeconfig
          kubectl --kubeconfig=/tmp/workload-kubeconfig apply -f /tmp/ua-ezkfWorkloadDeploy.yml
        dest: /tmp/ua-install.sh
        mode: 0x755
