---
- name: Prepare UA nodes
  hosts: ua_controllers:ua_workers
  become: true

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ../common/handlers.yml

  tasks:
    - name: Ensure the nodes are prepared
      ansible.builtin.import_tasks:
        file: ../common/prepare.yml

    - name: Install the required packages
      ansible.builtin.package:
        name:
          - nfs-utils
          - policycoreutils-python-utils
          - conntrack-tools
          - jq
          - tar
        state: present

    - name: Ensure iscsi utils
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          dnf --setopt=tsflags=noscripts install -y -q iscsi-initiator-utils
          echo "InitiatorName=$(/sbin/iscsi-iname)" | sudo tee -a /etc/iscsi/initiatorname.iscsi
        creates: /etc/iscsi/initiatorname.iscsi

    - name: Enable and start iscsid
      ansible.builtin.service:
        name: iscsid
        enabled: true
        state: started

    - name: Add the ip_tables module
      community.general.modprobe:
        name: ip_tables
        state: present

    - name: Configure firewalld backend
      ansible.builtin.lineinfile:
        path: /etc/firewalld/firewalld.conf
        regexp: 'FirewallBackend=.*'
        line: 'FirewallBackend=iptables/'
      when: "'firewalld' in services"
      notify: Restart firewalld

    - name: Turn off tx-checksum on eth0
      ansible.builtin.command: /sbin/ethtool -K eth0 tx-checksum-ip-generic off
      changed_when: "ethtool_out.stdout | length > 0"
      register: ethtool_out
      when: "'firewalld' in services"
      notify: Restart firewalld
