---
- name: Prepare external Data Fabric
  hosts: datafabric[0]
  become: true

  vars:
    sshusername: "{{ settings['username'] }}"
    sshpassword: "{{ settings['password'] }}"
    pwd_alias: "{{ lookup('ansible.builtin.password', './df_files/ezua.password', length=12) }}"
    ezua_df_username: ezua
    ezua_mount_path: /ezua

  tasks:
    - name: Ensure group
      ansible.builtin.group:
        name: "{{ ezua_df_username }}"
        state: present

    - name: Ensure user
      ansible.builtin.user:
        name: "{{ ezua_df_username }}"
        password: "{{ pwd_alias | password_hash('sha512') }}"
        group: "{{ ezua_df_username }}"
        home: "/home/{{ ezua_df_username }}"
        shell: /bin/bash

    - name: Setup DF credentials
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          echo "{{ ezdf['password'] }}" | maprlogin password -user {{ ezdf['user'] }}
          maprcli acl edit -type cluster -user {{ ezua_df_username }}:login,cv
          maprcli volume create -name ezua-base-volume -path {{ ezua_mount_path }} -type rw -json \
            -rootdiruser {{ ezua_df_username }} -rootdirgroup {{ ezua_df_username }} -createparent 1 || true
          maprlogin generateticket -type tenant -user {{ ezua_df_username }} -out /tmp/maprtenantticket
          # echo "{{ pwd_alias }}" | maprlogin password -user {{ ezua_df_username }}
        creates: "/tmp/maprtenantticket"

    - name: Get CLDB nodes
      ansible.builtin.shell:
        cmd: "/opt/mapr/bin/maprcli node list -columns hn -filter svc==cldb -json > /tmp/cldb_nodes.json"
        creates: "/tmp/cldb_nodes.json"

    - name: Get REST nodes
      ansible.builtin.shell:
        cmd: "/opt/mapr/bin/maprcli node list -columns hn -filter svc==apiserver -json > /tmp/rest_nodes.json"
        creates: "/tmp/rest_nodes.json"

    - name: Get S3 nodes
      ansible.builtin.shell:
        cmd: "/opt/mapr/bin/maprcli node list -columns hn -filter svc==s3server -json > /tmp/s3_nodes.json"
        creates: "/tmp/s3_nodes.json"

    - name: Create S3 keys
      ansible.builtin.shell:
        cmd: "maprcli s3keys generate -domainname primary -accountname default -username {{ ezua_df_username }} -json > /tmp/s3_keys.json"
        creates: "/tmp/s3_keys.json"

    - name: Save settings for DF
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "./df_files/{{ item.file }}"
        mode: "0o644"
      delegate_to: localhost
      with_items:
        - { file: 'username', content: "{{ ezua_df_username }}" }
        - { file: 'password', content: "{{ pwd_alias }}" }
        - { file: 'mount_path', content: "{{ ezua_mount_path }}" }

    - name: Get DF files
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: ./df_files/
        flat: true
      with_items:
        - "/opt/mapr/conf/ca/chain-ca.pem"
        - "/tmp/maprtenantticket"
        - "/tmp/cldb_nodes.json"
        - "/tmp/rest_nodes.json"
        - "/tmp/s3_nodes.json"
        - "/tmp/s3_keys.json"
