---
- name: Prepare external Data Fabric
  hosts: datafabric[0]
  
  vars:
    - sshusername: "{{ settings['username'] | default('mapr') }}"
    - sshpassword: "{{ settings['password'] | default('mapr123') }}"
    - ezua_user: ezua
    - mount_path: /ezua
    - pwd_alias: "{{ lookup('password', 'length=12 chars=ascii_letters') }}"
    - ezdf: "{{ ezdf | from_json }}"

  tasks:
    - name: Ensure user
      ansible.builtin.user:
        name: "{{ ezua_user }}"
        password: "{{ pwd_alias }}"
        group: "{{ ezua_user }}"
        home: "/home/{{ ezua_user }}"
        shell: /bin/bash
    
    - name: Setup cluster credentials
      ansible.builtin.shell:
        cmd: |
          echo "{{ pwd_alias }}" | maprlogin password -user "{{ ezua_user }}"
          echo "{{ mapr_password }}" | maprlogin password -user "{{ mapr_user }}"
          maprcli acl edit -type cluster -user "{{ ezua_user }}":login,cv
          maprcli volume create -name ezua-base-volume-"{{ ezua_user }}" -path "{{ mount_path }}" -type rw -json -rootdiruser "{{ ezua_user }}" -rootdirgroup "{{ ezua_user }}" -createparent 1
          maprlogin generateticket -type tenant -user "{{ ezua_user }}" -out /tmp/maprtenantticket-"{{ ezua_user }}"

    - name: Get CA
      ansible.builtin.fetch:
        src: /opt/mapr/conf/ca/chain-ca.pem
        dest: ./df_files
      
    - name: Get CLDB nodes
      ansible.builtin.shell:
        cmd: "maprcli node list -columns hn -filter svc==cldb"
      register: cldb_cmd

    - ansible.builtin.set_fact:
        cldb_hosts: "{{ cldb_cmd.stdout }}"