---
- name: Prepare external Data Fabric
  hosts: datafabric[0]
  become: true

  vars:
    sshusername: "{{ settings['username'] }}"
    sshpassword: "{{ settings['password'] }}"
    ezua_user: ezua
    mount_path: /ezua
    pwd_alias: "{{ lookup('ansible.builtin.password', './df_files/ezua.password', length=12) }}"
    ezdf: "{{ ezdf | from_json }}"

  tasks:
    - name: Ensure group
      ansible.builtin.group:
        name: "{{ ezua_user }}"
        state: present

    - name: Ensure user
      ansible.builtin.user:
        name: "{{ ezua_user }}"
        password: "{{ pwd_alias | password_hash('sha512') }}"
        group: "{{ ezua_user }}"
        home: "/home/{{ ezua_user }}"
        shell: /bin/bash

    - name: Setup cluster credentials
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          echo "{{ ezdf['password'] }}" | maprlogin password -user {{ ezdf['user'] }}
          maprcli acl edit -type cluster -user {{ ezua_user }}:login,cv
          maprcli volume create -name ezua-base-volume-{{ ezua_user }} -path {{ mount_path }} -type rw -json \
          -rootdiruser {{ ezua_user }} -rootdirgroup {{ ezua_user }} -createparent 1 || true
          maprlogin generateticket -type tenant -user {{ ezua_user }} -out /tmp/maprtenantticket-{{ ezua_user }}
          echo "{{ pwd_alias }}" | maprlogin password -user {{ ezua_user }}
        creates: "/tmp/maprtenantticket-{{ ezua_user }}"

    - name: Get CA
      ansible.builtin.fetch:
        src: /opt/mapr/conf/ca/chain-ca.pem
        dest: ./df_files

    - name: Get CLDB nodes
      ansible.builtin.command: "/opt/mapr/bin/maprcli node list -columns hn -filter svc==cldb -json"
      register: cldb_cmd
      changed_when: cldb_cmd.rc != 0

    - name: Register CLDB hosts
      ansible.builtin.set_fact:
        cldb_hosts: "{{ cldb_cmd.stdout | from_json | community.general.json_query('data[*].hostname') }}"

    - name: Create S3 keys
      ansible.builtin.shell:
        cmd: "maprcli s3keys generate -domainname primary -accountname default -username {{ ezua_user }} -json > /tmp/s3_keys-{{ ezua_user }}"
        creates: "/tmp/s3_keys-{{ ezua_user }}"
      register: s3_access_key_cmd

    - name: Get S3 keys
      ansible.builtin.slurp:
        src: "/tmp/s3_keys-{{ ezua_user }}"
      register: access_key_file

    - name: Register S3 keys
      ansible.builtin.set_fact:
        s3_access_key: "{{ (access_key_file['content'] | b64decode | from_json)['data'][0]['accesskey'] }}"
        s3_secret_key: "{{ (access_key_file['content'] | b64decode | from_json)['data'][0]['secretkey'] }}"

    - name: Get files
      ansible.builtin.fetch:
        src: "{{ item }}"
        dest: ./df_files
        mode: "0o600"
      with_items:
        - "/tmp/maprtenantticket-{{ ezua_user }}"
        - "/tmp/s3_keys-{{ ezua_user }}"
