---

- name: Prepare DF nodes
  ansible.builtin.import_playbook: prepare.yml

- name: Install Data Fabric
  hosts: datafabric[0]
  become: true

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ../common/handlers.yml

  tasks:
    - name: Get installer script
      ansible.builtin.get_url:
        url: "{{ df_repo | default('https://package.ezmeral.hpe.com/releases') }}/installer/redhat/mapr-setup.sh"
        dest: /tmp/mapr-setup.sh
        mode: '0o755'

    - name: Run Installer
      ansible.builtin.command:
        cmd: "/tmp/mapr-setup.sh -y -r {{ df_repo if df_repo.endswith('/') else df_repo + '/' }}"
        creates: "/opt/mapr/installer/bin/mapr-installer-cli"
      register: installer_setup

    - name: Get host FQDNs
      ansible.builtin.set_fact:
        mapr_hosts: "{{ groups['datafabric'] | map('extract', hostvars, ['ansible_fqdn']) | list }}"

    - name: Copy Stanza for Installation
      ansible.builtin.template:
        src: df-stanza.yml.j2
        dest: /tmp/mapr-stanza.yaml
        mode: "0o644"
      vars:
        mapr_hostnames: "{{ mapr_hosts | to_nice_yaml(indent=4) | trim | indent(4, first=true) }}"
        mapr_disks: "{{ df_disks | split(',') | to_nice_yaml(indent=4) | trim | indent(4, first=true) }}"

    - name: Wait for installer to be ready
      ansible.builtin.wait_for:
        port: 9443
        host: 127.0.0.1
        connect_timeout: 3
        delay: 5
        timeout: 120

    - name: Go get some coffee/tea
      ansible.builtin.debug:
        msg: "This will take some time, you can monitor the status at: https://mapr:mapr@{{ groups.datafabric.0 }}:9443/"

    - name: Start installation using stanza
      ansible.builtin.command:
        cmd: "/opt/mapr/installer/bin/mapr-installer-cli install -nvpf -t /tmp/mapr-stanza.yaml -u mapr:mapr@127.0.0.1:9443"
        creates: "/opt/mapr/conf/mapr-clusters.conf"

    - name: Ensure admin password
      ansible.builtin.user:
        name: "{{ df_username }}"
        password: "{{ df_password | password_hash('sha512') }}"

    - name: Copy license file
      ansible.builtin.copy:
        src: ../../LatestDemoLicense-M7.txt
        dest: /tmp/LatestDemoLicense-M7.txt
        mode: '0o400'
        owner: root
      notify: Install license
