---
- name: Install Data Fabric
  hosts: datafabric[0]
  become: true
  gather_facts: false


  vars:
    - mapr_core_version: 7.8.0
    - mapr_mep_version: 9.3.0
    - sshusername: "{{ settings['username'] | default('mapr') }}"
    - sshpassword: "{{ settings['password'] | default('mapr123') }}"
    - clustername: "{{ settings ['cluster_name'] | default('datafabric') }}"
    - mapr_hosts: "{{ ip_list | to_nice_yaml(indent=4) | trim | indent(4, first=true) }}"
    - disks: "{{ ezdf['disks'] | split(',') | to_nice_yaml(indent=4) | trim | indent(4, first=true) }}"


  tasks:
    - name: Set Repository
    # TODO: if no repo provided, default to MapR Repo
      ansible.builtin.debug:
        msg: "{{ ezdf.repo }}"

    - name: Get installer script
      ansible.builtin.get_url:
        url: "{{ ezdf.repo }}/installer/redhat/mapr-setup.sh"
        dest: /tmp/mapr-setup.sh
        mode: '0755'

    - name: Run Installer
      ansible.builtin.shell:
        cmd: "/tmp/mapr-setup.sh -y -r {{ ezdf.repo | regex_replace('\\/$', '') }}"
        creates: "/opt/mapr/installer/bin/mapr-installer-cli"

    - name: Collect IPs from group
      set_fact:
        ip_list: >-
          {{ groups['datafabric'] | map('extract', hostvars, ['ansible_host']) | list }}

    - name: Copy Stanza for Installation
      ansible.builtin.template:
        src: ../../templates/df-stanza.yml.j2
        dest: /tmp/mapr-stanza.yaml

    - name: Start installation using Stanza
      ansible.builtin.shell:
        cmd: "/opt/mapr/installer/bin/mapr-installer-cli install -nvp -t /tmp/mapr-stanza.yaml -u mapr:mapr@127.0.0.1:9443"
        creates: "/opt/mapr/conf/mapr-clusters.conf"
