---
- name: Prepare DF nodes
  hosts: datafabric
  become: true

  handlers:
    - name: Import handlers
      import_tasks: ../common/handlers.yml

  tasks:
    - name: Ensure the nodes are prepared
      ansible.builtin.import_tasks:
          file: ../common/prepare.yml
