---
- name: Remove VMs using terraform
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Destroy resources using terraform
      cloud.terraform.terraform:
        project_path: '../../tf'
        complex_vars: yes
        state: absent

    - name: Delete artifacts
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/clusterConfig.yaml
        - /tmp/ezkf-input.yaml
        - /tmp/ezkf-orch-status.txt
        - /tmp/ezkfWorkloadDeploy.yaml
        - /tmp/hostPoolConfig.yaml
        - /tmp/mgmt-kubeconfig
        - /tmp/prechecksStatus.txt
        - /tmp/ua-prechecks.yaml
