---
# handlers file for common

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
